name: Publish Package to npmjs
on:
  push:
    tags:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: publish @pivot-lang/create-monaco
    steps:
      - uses: actions/checkout@v3 
          override: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install pck
        run: cd /src/hooks/monaco && npm i
      - name: transform index.ts
        run:  tsc
      # Setup .npmrc file to publish to npm
      - run: npm version patch && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
