name: Publish Package to npmjs
on:
  push:
    tags:
      - 'm*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: publish @pivot-lang/create-monaco
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: |
          cd src/hooks/monaco && pnpm i
          pnpm build
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # Setup .npmrc file to publish to npm

      - run: |
          cd src/hooks/monaco && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
