name: Build Vue
on:
  push:
    branches:
    - master
    - release/*
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - id: Build-Vue
      run: |
        pnpm install
        pnpm build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
    - uses: Pivot-Studio/action-qiniu-upload@master
      with:
        # Your qiniu access key, required.
        access_key: ${{ secrets.QINIU_ACCESS_KEY }}

        # Your qiniu secret key, required.
        secret_key: ${{ secrets.QINIU_SECRET_KEY }}

        # Bucket name, required.
        bucket: ${{ secrets.QINIU_BUCKET }}

        # The local directory (or file) you want to upload to bucket.
        # Default: './'
        source_dir: 'dist'

        # The directory inside of the bucket you want to upload to, namely key prefix prepended to dest file key.
        # Default: '/'
        dest_dir: '/'

        # Whether to ignore source maps.
        # Default: true
        ignore_source_map: true